# Generated by Django 4.0.6 on 2022-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Document'),
        ),
    ]
