# Generated by Django 4.0.6 on 2022-07-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='title',
        ),
    ]
