# Generated by Django 4.0.6 on 2022-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_email_student_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
