# Generated by Django 4.0.6 on 2022-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
