# Generated by Django 4.0.6 on 2022-07-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_phone_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
